# Generated by Django 5.0.4 on 2024-05-12 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
