# Generated by Django 5.0.4 on 2024-04-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
